//
// auto-generated by ops.py//

//header
#define OPS_1D
#define OPS_API 2
#include "ops_lib_core.h"
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif
#include "user_types.h"

// global constants
extern double c0;
extern double rc0;
extern double rc1;
extern double rc2;
extern double rc3;
extern int nx0;
extern double deltai0;
extern double deltat;

void ops_init_backend() {}

//user kernel files
#include "complex_numbers_block0_5_kernel_cpu_kernel.cpp"
#include "complex_numbers_block0_4_kernel_cpu_kernel.cpp"
#include "complex_numbers_block0_0_kernel_cpu_kernel.cpp"
#include "complex_numbers_block0_1_kernel_cpu_kernel.cpp"
#include "complex_numbers_block0_2_kernel_cpu_kernel.cpp"
#include "complex_numbers_block0_3_kernel_cpu_kernel.cpp"
#include "complex_numbers_block0_cn_kernel_cpu_kernel.cpp"
