//
// auto-generated by ops.py//

#include "./OpenACC/mgrid_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "mgrid_populate_kernel_1_openacc_kernel_c.c"
#include "mgrid_prolong_kernel_openacc_kernel_c.c"
#include "prolong_check_openacc_kernel_c.c"
#include "mgrid_populate_kernel_3_openacc_kernel_c.c"
#include "mgrid_restrict_kernel_openacc_kernel_c.c"
#include "restrict_check_openacc_kernel_c.c"
