//
// auto-generated by ops.py//

#include "./OpenACC/mblock_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "mblock_populate_kernel_openacc_kernel_c.c"
