//
// auto-generated by ops.py//

#include "./OpenACC/access_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "access_populate_kernel_openacc_kernel_c.c"
