//
// auto-generated by ops.py
//

int xdim0_complex_numbers_block0_cn_kernel;


//user function



void complex_numbers_block0_cn_kernel_c_wrapper(
  double * restrict phi_p,
  double * restrict real_g,
  double * restrict imaginary_g,
  int x_size) {
  double real_0 = real_g[0];
  double imaginary_0 = imaginary_g[0];
  #pragma omp parallel for reduction(+:real_0) reduction(+:imaginary_0)
  for ( int n_x=0; n_x<x_size; n_x++ ){
    double real[1];
    real[0] = 0;
    double imaginary[1];
    imaginary[0] = 0;
    const ptr_double phi = { phi_p + n_x*1};
    
    double __complex__ z = 1.0I;
    double __complex__ coeff = z;

    *real = *real + OPS_ACC(phi, 0);
    coeff = coeff*z;
    *real = *real + __real__ coeff*OPS_ACC(phi, 0);
    *imaginary = *imaginary + __imag__ coeff*OPS_ACC(phi, 0);

    real_0 +=real[0];
    imaginary_0 +=imaginary[0];
  }
  real_g[0] = real_0;
  imaginary_g[0] = imaginary_0;
}
