//
// auto-generated by ops.py
//

int xdim0_complex_numbers_block0_2_kernel;
int xdim1_complex_numbers_block0_2_kernel;
int xdim2_complex_numbers_block0_2_kernel;


//user function



void complex_numbers_block0_2_kernel_c_wrapper(
  double * restrict phi_old_p,
  double * restrict wk1_p,
  double * restrict phi_p,
  const double * restrict rknew,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double phi_old = { phi_old_p + n_x*1};
    const ptr_double wk1 = { wk1_p + n_x*1};
    ptr_double phi = { phi_p + n_x*1};
    
OPS_ACC(phi, 0) = deltat*rknew[0]*OPS_ACC(wk1, 0) + OPS_ACC(phi_old, 0);

  }
}
