//
// auto-generated by ops.py
//

int xdim0_complex_numbers_block0_4_kernel;
int xdim1_complex_numbers_block0_4_kernel;


//user function



void complex_numbers_block0_4_kernel_c_wrapper(
  double * restrict phi_p,
  double * restrict phi_old_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double phi = { phi_p + n_x*1};
    ptr_double phi_old = { phi_old_p + n_x*1};
    
OPS_ACC(phi_old, 0) = OPS_ACC(phi, 0);

  }
}
