//
// auto-generated by ops.py
//

int xdim0_complex_numbers_block0_1_kernel;
int xdim1_complex_numbers_block0_1_kernel;


//user function



void complex_numbers_block0_1_kernel_c_wrapper(
  double * restrict wk0_p,
  double * restrict wk1_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double wk0 = { wk0_p + n_x*1};
    ptr_double wk1 = { wk1_p + n_x*1};
    
OPS_ACC(wk1, 0) = -c0*OPS_ACC(wk0, 0);

  }
}
