//
// auto-generated by ops.py
//

int xdim0_complex_numbers_block0_3_kernel;
int xdim1_complex_numbers_block0_3_kernel;


//user function



void complex_numbers_block0_3_kernel_c_wrapper(
  double * restrict wk1_p,
  double * restrict phi_old_p,
  const double * restrict rkold,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double wk1 = { wk1_p + n_x*1};
    ptr_double phi_old = { phi_old_p + n_x*1};
    
OPS_ACC(phi_old, 0) = deltat*rkold[0]*OPS_ACC(wk1, 0) + OPS_ACC(phi_old, 0);

  }
}
