//
// auto-generated by ops.py
//

int xdim0_complex_numbers_block0_0_kernel;
int xdim1_complex_numbers_block0_0_kernel;


//user function



void complex_numbers_block0_0_kernel_c_wrapper(
  double * restrict phi_p,
  double * restrict wk0_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double phi = { phi_p + n_x*1};
    ptr_double wk0 = { wk0_p + n_x*1};
    
OPS_ACC(wk0, 0) = ((rc0)*OPS_ACC(phi, -4) - rc1*OPS_ACC(phi, -3) + (rc2)*OPS_ACC(phi, -2) - rc3*OPS_ACC(phi, -1) + (rc3)*OPS_ACC(phi, 1) - rc2*OPS_ACC(phi, 2) + (rc1)*OPS_ACC(phi, 3) - rc0*OPS_ACC(phi, 4))/deltai0;

  }
}
