//
// auto-generated by ops.py
//

int xdim0_complex_numbers_block0_5_kernel;


//user function



void complex_numbers_block0_5_kernel_c_wrapper(
  double * restrict phi_p,
  int * restrict idx,
  int arg_idx0, 
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int idx[] = {arg_idx0+n_x};
    ptr_double phi = { phi_p + n_x*1};
    
OPS_ACC(phi, 0) = sin(2*deltai0*idx[0]*M_PI);

  }
}
