//
// auto-generated by ops.py//

#include "./OpenACC/adi_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "init_kernel_openacc_kernel_c.c"
#include "preproc_kernel_openacc_kernel_c.c"
