//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_init_kernel;
int ydim0_init_kernel;

//user function
inline 
void init_kernel(ptr_double val,
  int *idx){
  if(idx[0]==0 || idx[0]==nx-1 || idx[1]==0 || idx[1]==ny-1 || idx[2]==0 || idx[2]==nz-1)
    OPS_ACC(val, 0,0,0) = 1.0;
  else
    OPS_ACC(val, 0,0,0) = 0.0;
}


void init_kernel_c_wrapper(
  double *p_a0,
  int *p_a1,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_init_kernel*1*1 + n_z*xdim0_init_kernel*ydim0_init_kernel*1*1, xdim0_init_kernel, ydim0_init_kernel};
        init_kernel( ptr0,
          arg_idx );

      }
    }
  }
}
