//
// auto-generated by ops.py
//

int xdim0_initKernel;
int xdim1_initKernel;


//user function



void initKernel_c_wrapper(
  double * restrict uVel_p,
  double * restrict vVel_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      ptr_double uVel = { uVel_p + n_x*1 + n_y * xdim0_initKernel*1, xdim0_initKernel};
      ptr_double vVel = { vVel_p + n_x*1 + n_y * xdim1_initKernel*1, xdim1_initKernel};
      
    OPS_ACC(uVel, 0, 0) =
        0.75 -
        1 / (4 * (1 + exp((-4 * idx[0] * h + 4 * idx[1] * h) * Re / 32)));
    OPS_ACC(vVel, 0, 0) =
        0.75 +
        1 / (4 * (1 + exp((-4 * idx[0] * h + 4 * idx[1] * h) * Re / 32)));

    }
  }
}
