//
// auto-generated by ops.py//

#include "./OpenACC/adi_burger_common.h"

#include <openacc.h>

void ops_init_backend() {acc_set_device_num(ops_get_proc()%acc_get_num_devices(acc_device_nvidia),acc_device_nvidia); }

void ops_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
  ops_execute(OPS_instance::getOPSInstance());
  if (!strcmp(name,"nx")) {
    nx = *(int*)dat;
  }
  else
  if (!strcmp(name,"ny")) {
    ny = *(int*)dat;
  }
  else
  if (!strcmp(name,"Re")) {
    Re = *(double*)dat;
  }
  else
  if (!strcmp(name,"h")) {
    h = *(double*)dat;
  }
  else
  if (!strcmp(name,"r1")) {
    r1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"r2")) {
    r2 = *(double*)dat;
  }
  else
  {
    throw OPSException(OPS_RUNTIME_ERROR, "error: unknown const name");
  }
}

//user kernel files
#include "initKernel_openacc_kernel.cpp"
#include "preprocessX_openacc_kernel.cpp"
#include "preprocessY_openacc_kernel.cpp"
