//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_initKernel;
int xdim1_initKernel;

//user function
inline 
void initKernel(ptr_double uVel,
  ptr_double vVel,
  int *idx) {
    OPS_ACC(uVel, 0, 0) =
        0.75 -
        1 / (4 * (1 + exp((-4 * idx[0] * h + 4 * idx[1] * h) * Re / 32)));
    OPS_ACC(vVel, 0, 0) =
        0.75 +
        1 / (4 * (1 + exp((-4 * idx[0] * h + 4 * idx[1] * h) * Re / 32)));
}


void initKernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  int *p_a2,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_initKernel*1*1, xdim0_initKernel};
      ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_initKernel*1*1, xdim1_initKernel};
      initKernel( ptr0,
          ptr1,arg_idx );

    }
  }
}
