//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_preprocessY;
int xdim1_preprocessY;
int xdim3_preprocessY;
int xdim4_preprocessY;
int xdim5_preprocessY;
int xdim6_preprocessY;
int xdim7_preprocessY;
int xdim8_preprocessY;
int xdim9_preprocessY;

//user function
inline 
void preprocessY(const ptr_double u,
  const ptr_double v,
  const double *time,
  ptr_double a,
  ptr_double b,
  ptr_double c,
  ptr_double du,
  ptr_double dv,
  ACC<double> resU,
  ACC<double> resV,
  int *idx) {
    OPS_ACC(resU, 0, 0) = 0;
    OPS_ACC(resV, 0, 0) = 0;
    if (idx[0] == 0 || idx[0] == nx - 1 || idx[1] == 0 || idx[1] == ny - 1) {
        OPS_ACC(a, 0, 0) = 0;
        OPS_ACC(b, 0, 0) = 1;
        OPS_ACC(c, 0, 0) = 0;
        OPS_ACC(du, 0, 0) =
            0.75 -
            1 / (4 * (1 + exp((-4 * idx[0] * h + 4 * idx[1] * h - (*time)) *
                              Re / 32)));
        OPS_ACC(dv, 0, 0) =
            0.75 +
            1 / (4 * (1 + exp((-4 * idx[0] * h + 4 * idx[1] * h - (*time)) *
                              Re / 32)));
    } else {
        OPS_ACC(a, 0, 0) = -r1 * OPS_ACC(v, 0, 0) - r2;
        OPS_ACC(b, 0, 0) = 1 + 2 * r2;
        OPS_ACC(c, 0, 0) = -r1 * OPS_ACC(v, 0, 0) + r2;
        OPS_ACC(du, 0, 0) = (r1 * OPS_ACC(u, 0, 0) + r2) * OPS_ACC(u, -1, 0) + (1 - 2 * r2) * OPS_ACC(u, 0, 0) +
                   (-r1 * OPS_ACC(u, 0, 0) + r2) * OPS_ACC(u, 1, 0);
        OPS_ACC(dv, 0, 0) = (r1 * OPS_ACC(u, 0, 0) + r2) * OPS_ACC(v, -1, 0) + (1 - 2 * r2) * OPS_ACC(v, 0, 0) +
                   (-r1 * OPS_ACC(u, 0, 0) + r2) * OPS_ACC(v, 1, 0);
    }
}


void preprocessY_c_wrapper(
  double *p_a0,
  double *p_a1,
  double p_a2,
  double *p_a3,
  double *p_a4,
  double *p_a5,
  double *p_a6,
  double *p_a7,
  double *p_a8,
  double *p_a9,
  int *p_a10,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a3,p_a4,p_a5,p_a6,p_a7,p_a8,p_a9)
  #pragma acc loop
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_preprocessY*1*1, xdim0_preprocessY};
      const ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_preprocessY*1*1, xdim1_preprocessY};
      ptr_double ptr3 = {  p_a3 + n_x*1*1 + n_y*xdim3_preprocessY*1*1, xdim3_preprocessY};
      ptr_double ptr4 = {  p_a4 + n_x*1*1 + n_y*xdim4_preprocessY*1*1, xdim4_preprocessY};
      ptr_double ptr5 = {  p_a5 + n_x*1*1 + n_y*xdim5_preprocessY*1*1, xdim5_preprocessY};
      ptr_double ptr6 = {  p_a6 + n_x*1*1 + n_y*xdim6_preprocessY*1*1, xdim6_preprocessY};
      ptr_double ptr7 = {  p_a7 + n_x*1*1 + n_y*xdim7_preprocessY*1*1, xdim7_preprocessY};
      ptr_double ptr8 = {  p_a8 + n_x*1*1 + n_y*xdim8_preprocessY*1*1, xdim8_preprocessY};
      ptr_double ptr9 = {  p_a9 + n_x*1*1 + n_y*xdim9_preprocessY*1*1, xdim9_preprocessY};
      preprocessY( ptr0,
          ptr1, &p_a2,
          ptr3,ptr4,
          ptr5,ptr6,
          ptr7,ptr8,
          ptr9,arg_idx );

    }
  }
}
