//
// auto-generated by ops.py
//

#define OPS_3D
#include <math.h>
#include "./MPI_inline/adi_common.h"
//user kernel files
#include "init_kernel_mpiinline_kernel_c.c"
#include "preproc_kernel_mpiinline_kernel_c.c"
