//
// auto-generated by ops.py
//

int xdim0_init_kernel;
int ydim0_init_kernel;


//user function



void init_kernel_c_wrapper(
  double * restrict val_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        ptr_double val = { val_p + n_x*1 + n_y * xdim0_init_kernel*1 + n_z * xdim0_init_kernel * ydim0_init_kernel*1, xdim0_init_kernel, ydim0_init_kernel};
        
  if(idx[0]==0 || idx[0]==nx-1 || idx[1]==0 || idx[1]==ny-1 || idx[2]==0 || idx[2]==nz-1)
    OPS_ACC(val, 0,0,0) = 1.0;
  else
    OPS_ACC(val, 0,0,0) = 0.0;

      }
    }
  }
}
