//
// auto-generated by ops.py//

#include "./OpenACC/lowdim_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "set_val_openacc_kernel_c.c"
#include "calc_openacc_kernel_c.c"
