//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_complex_numbers_block0_2_kernel;
int xdim1_complex_numbers_block0_2_kernel;
int xdim2_complex_numbers_block0_2_kernel;

//user function
inline 
void complex_numbers_block0_2_kernel(const ptr_double phi_old,
  const ptr_double wk1,
  ptr_double phi,
  const ACC<double> &rknew)
{
OPS_ACC(phi, 0) = deltat*rknew[0]*OPS_ACC(wk1, 0) + OPS_ACC(phi_old, 0);
}


void complex_numbers_block0_2_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double p_a3,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double ptr0 = {  p_a0 + n_x*1*1 };
    const ptr_double ptr1 = {  p_a1 + n_x*1*1 };
    ptr_double ptr2 = {  p_a2 + n_x*1*1 };
    complex_numbers_block0_2_kernel( ptr0,
          ptr1,ptr2,
           &p_a3 );

  }
}
