//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_complex_numbers_block0_cn_kernel;

//user function
inline 
void complex_numbers_block0_cn_kernel(const ptr_double phi,
  double *real,
  double *imaginary)
{
    double __complex__ z = 1.0I;
    double __complex__ coeff = z;

    *real = *real + OPS_ACC(phi, 0);
    coeff = coeff*z;
    *real = *real + __real__ coeff*OPS_ACC(phi, 0);
    *imaginary = *imaginary + __imag__ coeff*OPS_ACC(phi, 0);
}


void complex_numbers_block0_cn_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  int x_size) {
  double p_a1_0 = p_a1[0];
  double p_a2_0 = p_a2[0];
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0) reduction(+:p_a1_0) reduction(+:p_a2_0)
  #pragma acc loop reduction(+:p_a1_0) reduction(+:p_a2_0)
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double ptr0 = {  p_a0 + n_x*1*1 };
    complex_numbers_block0_cn_kernel( ptr0,
           &p_a1_0, &p_a2_0 );

  }
  p_a1[0] = p_a1_0;
  p_a2[0] = p_a2_0;
}
