//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_complex_numbers_block0_0_kernel;
int xdim1_complex_numbers_block0_0_kernel;

//user function
inline 
void complex_numbers_block0_0_kernel(const ptr_double phi,
  ptr_double wk0)
{
OPS_ACC(wk0, 0) = ((rc0)*OPS_ACC(phi, -4) - rc1*OPS_ACC(phi, -3) + (rc2)*OPS_ACC(phi, -2) - rc3*OPS_ACC(phi, -1) + (rc3)*OPS_ACC(phi, 1) - rc2*OPS_ACC(phi, 2) + (rc1)*OPS_ACC(phi, 3) - rc0*OPS_ACC(phi, 4))/deltai0;
}


void complex_numbers_block0_0_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double ptr0 = {  p_a0 + n_x*1*1 };
    ptr_double ptr1 = {  p_a1 + n_x*1*1 };
    complex_numbers_block0_0_kernel( ptr0,
          ptr1 );

  }
}
