//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_complex_numbers_block0_3_kernel;
int xdim1_complex_numbers_block0_3_kernel;

//user function
inline 
void complex_numbers_block0_3_kernel(const ptr_double wk1,
  ptr_double phi_old,
  const ACC<double> &rkold)
{
OPS_ACC(phi_old, 0) = deltat*rkold[0]*OPS_ACC(wk1, 0) + OPS_ACC(phi_old, 0);
}


void complex_numbers_block0_3_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  double p_a2,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double ptr0 = {  p_a0 + n_x*1*1 };
    ptr_double ptr1 = {  p_a1 + n_x*1*1 };
    complex_numbers_block0_3_kernel( ptr0,
          ptr1, &p_a2 );

  }
}
