//
// auto-generated by ops.py
//

#define OPS_3D
#include <math.h>
#include "./MPI_inline/adi_burger_3D_common.h"
//user kernel files
#include "initKernel_mpiinline_kernel_c.c"
#include "CopyUVW_mpiinline_kernel_c.c"
#include "preprocessX_mpiinline_kernel_c.c"
#include "preprocessY_mpiinline_kernel_c.c"
#include "preprocessZ_mpiinline_kernel_c.c"
