//
// auto-generated by ops.py
//

int xdim0_CopyUVW;
int ydim0_CopyUVW;
int xdim1_CopyUVW;
int ydim1_CopyUVW;
int xdim2_CopyUVW;
int ydim2_CopyUVW;
int xdim3_CopyUVW;
int ydim3_CopyUVW;
int xdim4_CopyUVW;
int ydim4_CopyUVW;
int xdim5_CopyUVW;
int ydim5_CopyUVW;


//user function



void CopyUVW_c_wrapper(
  double * restrict u_p,
  double * restrict v_p,
  double * restrict w_p,
  double * restrict uStar_p,
  double * restrict vStar_p,
  double * restrict wStar_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double u = { u_p + n_x*1 + n_y * xdim0_CopyUVW*1 + n_z * xdim0_CopyUVW * ydim0_CopyUVW*1, xdim0_CopyUVW, ydim0_CopyUVW};
        const ptr_double v = { v_p + n_x*1 + n_y * xdim1_CopyUVW*1 + n_z * xdim1_CopyUVW * ydim1_CopyUVW*1, xdim1_CopyUVW, ydim1_CopyUVW};
        const ptr_double w = { w_p + n_x*1 + n_y * xdim2_CopyUVW*1 + n_z * xdim2_CopyUVW * ydim2_CopyUVW*1, xdim2_CopyUVW, ydim2_CopyUVW};
        ptr_double uStar = { uStar_p + n_x*1 + n_y * xdim3_CopyUVW*1 + n_z * xdim3_CopyUVW * ydim3_CopyUVW*1, xdim3_CopyUVW, ydim3_CopyUVW};
        ptr_double vStar = { vStar_p + n_x*1 + n_y * xdim4_CopyUVW*1 + n_z * xdim4_CopyUVW * ydim4_CopyUVW*1, xdim4_CopyUVW, ydim4_CopyUVW};
        ptr_double wStar = { wStar_p + n_x*1 + n_y * xdim5_CopyUVW*1 + n_z * xdim5_CopyUVW * ydim5_CopyUVW*1, xdim5_CopyUVW, ydim5_CopyUVW};
        
    OPS_ACC(uStar, 0, 0, 0) = OPS_ACC(u, 0, 0, 0);
    OPS_ACC(vStar, 0, 0, 0) = OPS_ACC(v, 0, 0, 0);
    OPS_ACC(wStar, 0, 0, 0) = OPS_ACC(w, 0, 0, 0);

      }
    }
  }
}
