//
// auto-generated by ops.py
//

int xdim0_preprocessY;
int ydim0_preprocessY;
int xdim1_preprocessY;
int ydim1_preprocessY;
int xdim2_preprocessY;
int ydim2_preprocessY;
int xdim4_preprocessY;
int ydim4_preprocessY;
int xdim5_preprocessY;
int ydim5_preprocessY;
int xdim6_preprocessY;
int ydim6_preprocessY;
int xdim7_preprocessY;
int ydim7_preprocessY;
int xdim8_preprocessY;
int ydim8_preprocessY;
int xdim9_preprocessY;
int ydim9_preprocessY;
int xdim10_preprocessY;
int ydim10_preprocessY;
int xdim11_preprocessY;
int ydim11_preprocessY;
int xdim12_preprocessY;
int ydim12_preprocessY;


//user function



void preprocessY_c_wrapper(
  double * restrict u_p,
  double * restrict v_p,
  double * restrict w_p,
  const double * restrict time,
  double * restrict a_p,
  double * restrict b_p,
  double * restrict c_p,
  double * restrict du_p,
  double * restrict dv_p,
  double * restrict dw_p,
  double * restrict resU_p,
  double * restrict resV_p,
  double * restrict resW_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        const ptr_double u = { u_p + n_x*1 + n_y * xdim0_preprocessY*1 + n_z * xdim0_preprocessY * ydim0_preprocessY*1, xdim0_preprocessY, ydim0_preprocessY};
        const ptr_double v = { v_p + n_x*1 + n_y * xdim1_preprocessY*1 + n_z * xdim1_preprocessY * ydim1_preprocessY*1, xdim1_preprocessY, ydim1_preprocessY};
        const ptr_double w = { w_p + n_x*1 + n_y * xdim2_preprocessY*1 + n_z * xdim2_preprocessY * ydim2_preprocessY*1, xdim2_preprocessY, ydim2_preprocessY};
        ptr_double a = { a_p + n_x*1 + n_y * xdim4_preprocessY*1 + n_z * xdim4_preprocessY * ydim4_preprocessY*1, xdim4_preprocessY, ydim4_preprocessY};
        ptr_double b = { b_p + n_x*1 + n_y * xdim5_preprocessY*1 + n_z * xdim5_preprocessY * ydim5_preprocessY*1, xdim5_preprocessY, ydim5_preprocessY};
        ptr_double c = { c_p + n_x*1 + n_y * xdim6_preprocessY*1 + n_z * xdim6_preprocessY * ydim6_preprocessY*1, xdim6_preprocessY, ydim6_preprocessY};
        ptr_double du = { du_p + n_x*1 + n_y * xdim7_preprocessY*1 + n_z * xdim7_preprocessY * ydim7_preprocessY*1, xdim7_preprocessY, ydim7_preprocessY};
        ptr_double dv = { dv_p + n_x*1 + n_y * xdim8_preprocessY*1 + n_z * xdim8_preprocessY * ydim8_preprocessY*1, xdim8_preprocessY, ydim8_preprocessY};
        ptr_double dw = { dw_p + n_x*1 + n_y * xdim9_preprocessY*1 + n_z * xdim9_preprocessY * ydim9_preprocessY*1, xdim9_preprocessY, ydim9_preprocessY};
        ptr_double resU = { resU_p + n_x*1 + n_y * xdim10_preprocessY*1 + n_z * xdim10_preprocessY * ydim10_preprocessY*1, xdim10_preprocessY, ydim10_preprocessY};
        ptr_double resV = { resV_p + n_x*1 + n_y * xdim11_preprocessY*1 + n_z * xdim11_preprocessY * ydim11_preprocessY*1, xdim11_preprocessY, ydim11_preprocessY};
        ptr_double resW = { resW_p + n_x*1 + n_y * xdim12_preprocessY*1 + n_z * xdim12_preprocessY * ydim12_preprocessY*1, xdim12_preprocessY, ydim12_preprocessY};
        
    OPS_ACC(resU, 0, 0, 0) = 0;
    OPS_ACC(resV, 0, 0, 0) = 0;
    OPS_ACC(resW, 0, 0, 0) = 0;
    const double x{h * idx[0]};
    const double y{h * idx[1]};
    const double z{h * idx[2]};
    const double t{*time};
    if (idx[0] == 0 || idx[0] == nx - 1 || idx[1] == 0 || idx[1] == ny - 1 ||
        idx[2] == 0 || idx[2] == nz - 1) {
        OPS_ACC(a, 0, 0, 0) = 0;
        OPS_ACC(b, 0, 0, 0) = 1;
        OPS_ACC(c, 0, 0, 0) = 0;
        OPS_ACC(du, 0, 0, 0) = 2 * exp(-t / Re) * sin(x) * sin(y) * cos(z) /
                      (Re * (cos(x) * sin(y) * cos(z) + 1));
        OPS_ACC(dv, 0, 0, 0) = -2 * exp(-t / Re) * cos(x) * cos(y) * cos(z) /
                      (Re * (cos(x) * sin(y) * cos(z) + 1));
        OPS_ACC(dw, 0, 0, 0) = 2 * exp(-t / Re) * cos(x) * sin(y) * sin(z) /
                      (Re * (cos(x) * sin(y) * cos(z) + 1));
    } else {
        OPS_ACC(a, 0, 0, 0) = -r1 * OPS_ACC(v, 0, 0, 0) - r2;
        OPS_ACC(b, 0, 0, 0) = 1 + 2 * r2;
        OPS_ACC(c, 0, 0, 0) = r1 * OPS_ACC(v, 0, 0, 0) - r2;
        OPS_ACC(du, 0, 0, 0) = (r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(u, -1, 0, 0) +
                      (-r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(u, 1, 0, 0) +
                      (r1 * OPS_ACC(w, 0, 0, 0) + r2) * OPS_ACC(u, 0, 0, -1) +
                      (-r1 * OPS_ACC(w, 0, 0, 0) + r2) * OPS_ACC(u, 0, 0, 1) +
                      (1 - 4 * r2) * OPS_ACC(u, 0, 0, 0);
        OPS_ACC(dv, 0, 0, 0) = (r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(v, -1, 0, 0) +
                      (-r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(v, 1, 0, 0) +
                      (r1 * OPS_ACC(w, 0, 0, 0) + r2) * OPS_ACC(v, 0, 0, -1) +
                      (-r1 * OPS_ACC(w, 0, 0, 0) + r2) * OPS_ACC(v, 0, 0, 1) +
                      (1 - 4 * r2) * OPS_ACC(v, 0, 0, 0);
        OPS_ACC(dw, 0, 0, 0) = (r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(w, -1, 0, 0) +
                      (-r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(w, 1, 0, 0) +
                      (r1 * OPS_ACC(w, 0, 0, 0) + r2) * OPS_ACC(w, 0, 0, -1) +
                      (-r1 * OPS_ACC(w, 0, 0, 0) + r2) * OPS_ACC(w, 0, 0, 1) +
                      (1 - 4 * r2) * OPS_ACC(w, 0, 0, 0);
    }

      }
    }
  }
}
