//
// auto-generated by ops.py
//

int xdim0_calupwindeff_kernel;
int xdim1_calupwindeff_kernel;
int xdim2_calupwindeff_kernel;
int xdim3_calupwindeff_kernel;
int xdim4_calupwindeff_kernel;
int xdim5_calupwindeff_kernel;
int xdim6_calupwindeff_kernel;


//user function



void calupwindeff_kernel_c_wrapper(
  double * restrict cmp_p,
  double * restrict gt_p,
  double * restrict cf_p,
  double * restrict al_p,
  double * restrict ep2_p,
  double * restrict r_p,
  double * restrict eff_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    #ifdef OPS_SOA
    const ptrm_double cmp = { cmp_p + n_x*1, xdim0_calupwindeff_kernel};
    #else
    const ptrm_double cmp = { cmp_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    const ptrm_double gt = { gt_p + n_x*1, xdim1_calupwindeff_kernel};
    #else
    const ptrm_double gt = { gt_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    const ptrm_double cf = { cf_p + n_x*1, xdim2_calupwindeff_kernel};
    #else
    const ptrm_double cf = { cf_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    const ptrm_double al = { al_p + n_x*1, xdim3_calupwindeff_kernel};
    #else
    const ptrm_double al = { al_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    const ptrm_double ep2 = { ep2_p + n_x*1, xdim4_calupwindeff_kernel};
    #else
    const ptrm_double ep2 = { ep2_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    const ptrm_double r = { r_p + n_x*1, xdim5_calupwindeff_kernel};
    #else
    const ptrm_double r = { r_p + n_x*1, 9};
    #endif
    #ifdef OPS_SOA
    ptrm_double eff = { eff_p + n_x*1, xdim6_calupwindeff_kernel};
    #else
    ptrm_double eff = { eff_p + n_x*1, 3};
    #endif
    

		double e1 = (OPS_ACC(cmp, 0,0) * (OPS_ACC(gt, 0,0) + OPS_ACC(gt, 0,1)) - OPS_ACC(cf, 0,0) * OPS_ACC(al, 0,0)) * OPS_ACC(ep2, 0,0);
		double e2 = (OPS_ACC(cmp, 1,0) * (OPS_ACC(gt, 1,0) + OPS_ACC(gt, 1,1)) - OPS_ACC(cf, 1,0) * OPS_ACC(al, 1,0)) * OPS_ACC(ep2, 1,0);
		double e3 = (OPS_ACC(cmp, 2,0) * (OPS_ACC(gt, 2,0) + OPS_ACC(gt, 2,1)) - OPS_ACC(cf, 2,0) * OPS_ACC(al, 2,0)) * OPS_ACC(ep2, 2,0);

		OPS_ACC(eff, 0,0)=e1 * OPS_ACC(r, 0,0) + e2 * OPS_ACC(r, 1,0) + e3 * OPS_ACC(r, 2,0);
		OPS_ACC(eff, 1,0)=e1 * OPS_ACC(r, 3,0) + e2 * OPS_ACC(r, 4,0) + e3 * OPS_ACC(r, 5,0);
		OPS_ACC(eff, 2,0)=e1 * OPS_ACC(r, 6,0) + e2 * OPS_ACC(r, 7,0) + e3 * OPS_ACC(r, 8,0);

  }
}
