//
// auto-generated by ops.py
//

int xdim0_drhouupdx_kernel;
int xdim1_drhouupdx_kernel;
int xdim2_drhouupdx_kernel;
int xdim3_drhouupdx_kernel;


//user function



void drhouupdx_kernel_c_wrapper(
  double * restrict rhou_new_p,
  double * restrict rho_new_p,
  double * restrict rhoE_new_p,
  double * restrict rhou_res_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double rhou_new = { rhou_new_p + n_x*1};
    const ptr_double rho_new = { rho_new_p + n_x*1};
    const ptr_double rhoE_new = { rhoE_new_p + n_x*1};
    ptr_double rhou_res = { rhou_res_p + n_x*1};
    

			double fni = OPS_ACC(rhou_new, 0) * OPS_ACC(rhou_new, 0) / OPS_ACC(rho_new, 0) ;
			double p = gam1 * (OPS_ACC(rhoE_new, 0) - 0.5 * fni);
			fni = fni + p;
			double fnim1 = OPS_ACC(rhou_new, -1) * OPS_ACC(rhou_new, -1) / OPS_ACC(rho_new, -1);
			p = gam1 * (OPS_ACC(rhoE_new, -1) - 0.5 * fnim1);
			fnim1 = fnim1 + p;
			double fnim2 = OPS_ACC(rhou_new, -2) * OPS_ACC(rhou_new, -2) / OPS_ACC(rho_new, -2);
			p = gam1 * (OPS_ACC(rhoE_new, -2) - 0.5 * fnim2);
			fnim2 = fnim2 + p;
			double fnip1 = OPS_ACC(rhou_new, 1) * OPS_ACC(rhou_new, 1) / OPS_ACC(rho_new, 1);
			p = gam1 * (OPS_ACC(rhoE_new, 1) - 0.5 * fnip1);
			fnip1 = fnip1 + p;
			double fnip2 = OPS_ACC(rhou_new, 2) * OPS_ACC(rhou_new, 2) / OPS_ACC(rho_new, 2);
			p = gam1 * (OPS_ACC(rhoE_new, 2) - 0.5 * fnip2);
			fnip2 = fnip2 + p;

			double deriv = (fnim2 - fnip2 + 8.0* (fnip1 - fnim1))/(12.00*dx);
			OPS_ACC(rhou_res, 0) = deriv;

  }
}
