//
// auto-generated by ops.py
//

int xdim0_drhoudx_kernel;
int xdim1_drhoudx_kernel;


//user function



void drhoudx_kernel_c_wrapper(
  double * restrict rhou_new_p,
  double * restrict rho_res_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double rhou_new = { rhou_new_p + n_x*1};
    ptr_double rho_res = { rho_res_p + n_x*1};
    

        double fnim1 = OPS_ACC(rhou_new, -1);
        double fnim2 = OPS_ACC(rhou_new, -2);
        double fnip1 = OPS_ACC(rhou_new, 1);
        double fnip2 = OPS_ACC(rhou_new, 2);

        double deriv = (fnim2 - fnip2 + 8.0* (fnip1 - fnim1))/(12.00*dx);
        OPS_ACC(rho_res, 0) = deriv;

  }
}
