//
// auto-generated by ops.py
//

int xdim0_initialize_kernel;
int xdim1_initialize_kernel;
int xdim2_initialize_kernel;
int xdim3_initialize_kernel;
int xdim4_initialize_kernel;


//user function



void initialize_kernel_c_wrapper(
  double * restrict x_p,
  double * restrict rho_new_p,
  double * restrict rhou_new_p,
  double * restrict rhoE_new_p,
  double * restrict rhoin_p,
  int * restrict idx,
  int arg_idx0, 
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int idx[] = {arg_idx0+n_x};
    ptr_double x = { x_p + n_x*1};
    ptr_double rho_new = { rho_new_p + n_x*1};
    ptr_double rhou_new = { rhou_new_p + n_x*1};
    ptr_double rhoE_new = { rhoE_new_p + n_x*1};
    ptr_double rhoin = { rhoin_p + n_x*1};
    
  OPS_ACC(x, 0) = xmin + (idx[0]-2) * dx;
  if (OPS_ACC(x, 0) >= -4.0){
		OPS_ACC(rho_new, 0) = 1.0 + eps * sin(lambda *OPS_ACC(x, 0));
		OPS_ACC(rhou_new, 0) = ur * OPS_ACC(rho_new, 0);
		OPS_ACC(rhoE_new, 0) = (pr / gam1) + 0.5 * pow(OPS_ACC(rhou_new, 0),2)/OPS_ACC(rho_new, 0);
	}
	else {
		OPS_ACC(rho_new, 0) = rhol;
		OPS_ACC(rhou_new, 0) = ul2 * OPS_ACC(rho_new, 0);
		OPS_ACC(rhoE_new, 0) = (pl / gam1) + 0.5 * pow(OPS_ACC(rhou_new, 0),2)/OPS_ACC(rho_new, 0);
	}

	OPS_ACC(rhoin, 0) = gam1 * (OPS_ACC(rhoE_new, 0) - 0.5 * OPS_ACC(rhou_new, 0) * OPS_ACC(rhou_new, 0) / OPS_ACC(rho_new, 0));


  }
}
