//
// auto-generated by ops.py
//

int xdim0_test_kernel;


//user function



void test_kernel_c_wrapper(
  double * restrict rho_new_p,
  double * restrict rms_g,
  int x_size) {
  double rms_0 = rms_g[0];
  #pragma omp parallel for reduction(+:rms_0)
  for ( int n_x=0; n_x<x_size; n_x++ ){
    double rms[1];
    rms[0] = 0;
    const ptr_double rho_new = { rho_new_p + n_x*1};
    

  rms[0] = rms[0] + pow (OPS_ACC(rho_new, 0), 2.0);

    rms_0 +=rms[0];
  }
  rms_g[0] = rms_0;
}
