//
// auto-generated by ops.py
//

int xdim0_update_kernel;
int xdim1_update_kernel;
int xdim2_update_kernel;
int xdim3_update_kernel;


//user function



void update_kernel_c_wrapper(
  double * restrict rho_new_p,
  double * restrict rhou_new_p,
  double * restrict rhoE_new_p,
  double * restrict s_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    ptr_double rho_new = { rho_new_p + n_x*1};
    ptr_double rhou_new = { rhou_new_p + n_x*1};
    ptr_double rhoE_new = { rhoE_new_p + n_x*1};
    #ifdef OPS_SOA
    const ptrm_double s = { s_p + n_x*1, xdim3_update_kernel};
    #else
    const ptrm_double s = { s_p + n_x*1, 3};
    #endif
    
		OPS_ACC(rho_new, 0)  = OPS_ACC(rho_new, 0)  + OPS_ACC(s, 0,0);
		OPS_ACC(rhou_new, 0) = OPS_ACC(rhou_new, 0) + OPS_ACC(s, 1,0);
		OPS_ACC(rhoE_new, 0) = OPS_ACC(rhoE_new, 0) + OPS_ACC(s, 2,0);

  }
}
