//
// auto-generated by ops.py
//

int xdim0_zerores_kernel;
int xdim1_zerores_kernel;
int xdim2_zerores_kernel;


//user function



void zerores_kernel_c_wrapper(
  double * restrict rho_res_p,
  double * restrict rhou_res_p,
  double * restrict rhoE_res_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    ptr_double rho_res = { rho_res_p + n_x*1};
    ptr_double rhou_res = { rhou_res_p + n_x*1};
    ptr_double rhoE_res = { rhoE_res_p + n_x*1};
    
      OPS_ACC(rho_res, 0) = 0.0;
      OPS_ACC(rhou_res, 0) = 0.0;
      OPS_ACC(rhoE_res, 0) = 0.0;

  }
}
