//
// auto-generated by ops.py
//

int xdim0_calvar_kernel;
int xdim1_calvar_kernel;
int xdim2_calvar_kernel;
int xdim3_calvar_kernel;
int xdim4_calvar_kernel;


//user function



void calvar_kernel_c_wrapper(
  double * restrict rho_new_p,
  double * restrict rhou_new_p,
  double * restrict rhoE_new_p,
  double * restrict workarray2_p,
  double * restrict workarray3_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double rho_new = { rho_new_p + n_x*1};
    const ptr_double rhou_new = { rhou_new_p + n_x*1};
    const ptr_double rhoE_new = { rhoE_new_p + n_x*1};
    ptr_double workarray2 = { workarray2_p + n_x*1};
    ptr_double workarray3 = { workarray3_p + n_x*1};
    
  double p, rhoi, u;
  rhoi = 1/OPS_ACC(rho_new, 0);
  u = OPS_ACC(rhou_new, 0) * rhoi;
  p = gam1 * (OPS_ACC(rhoE_new, 0) - 0.5 * OPS_ACC(rho_new, 0)* u * u);

  OPS_ACC(workarray2, 0) = p + OPS_ACC(rhou_new, 0) * u ;
  OPS_ACC(workarray3, 0) = (p + OPS_ACC(rhoE_new, 0)) * u ;
  
  }
}
