//
// auto-generated by ops.py
//

int xdim0_checkop_kernel;
int xdim1_checkop_kernel;
int xdim2_checkop_kernel;


//user function



void checkop_kernel_c_wrapper(
  double * restrict rho_new_p,
  double * restrict x_p,
  double * restrict rhoin_p,
  double * restrict pre_g,
  double * restrict post_g,
  int * restrict num_g,
  int x_size) {
  double pre_0 = pre_g[0];
  double post_0 = post_g[0];
  int num_0 = num_g[0];
  #pragma omp parallel for reduction(+:pre_0) reduction(+:post_0) reduction(+:num_0)
  for ( int n_x=0; n_x<x_size; n_x++ ){
    double pre[1];
    pre[0] = 0;
    double post[1];
    post[0] = 0;
    int num[1];
    num[0] = 0;
    const ptr_double rho_new = { rho_new_p + n_x*1};
    const ptr_double x = { x_p + n_x*1};
    const ptr_double rhoin = { rhoin_p + n_x*1};
    
  double diff;
  diff = (OPS_ACC(rho_new, 0) - OPS_ACC(rhoin, 0));
  if(fabs(diff)<0.01 && OPS_ACC(x, 0) > -4.1){
    *post = *post + diff*diff;
    *num = *num + 1;

  }
  else
    *pre = *pre + (OPS_ACC(rho_new, 0) - rhol)* (OPS_ACC(rho_new, 0) - rhol);

    pre_0 +=pre[0];
    post_0 +=post[0];
    num_0 +=num[0];
  }
  pre_g[0] = pre_0;
  post_g[0] = post_0;
  num_g[0] = num_0;
}
