//
// auto-generated by ops.py
//

int xdim0_gridgen_kernel;


//user function



void gridgen_kernel_c_wrapper(
  double * restrict x_p,
  int * restrict id,
  int arg_idx0, 
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int id[] = {arg_idx0+n_x};
    ptr_double x = { x_p + n_x*1};
    

  OPS_ACC(x, 0) = xt +  id[0] *dx;


  }
}
