//
// auto-generated by ops.py
//

int xdim0_limiter_kernel;
int xdim1_limiter_kernel;
int xdim2_limiter_kernel;


//user function



void limiter_kernel_c_wrapper(
  double * restrict al_p,
  double * restrict tht_p,
  double * restrict gt_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    #ifdef OPS_SOA
    const ptrm_double al = { al_p + n_x*1, xdim0_limiter_kernel};
    #else
    const ptrm_double al = { al_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    ptrm_double tht = { tht_p + n_x*1, xdim1_limiter_kernel};
    #else
    ptrm_double tht = { tht_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    ptrm_double gt = { gt_p + n_x*1, xdim2_limiter_kernel};
    #else
    ptrm_double gt = { gt_p + n_x*1, 3};
    #endif
    

  double aalm, aal, all, ar, gtt;
  for (int m=0; m < 3 ;m++) {
    aalm = fabs(OPS_ACC(al, m,-1));
    aal = fabs(OPS_ACC(al, m,0));
    OPS_ACC(tht, m,0) = fabs (aal - aalm) / (aal + aalm + del2);
    all = OPS_ACC(al, m,-1);
    ar = OPS_ACC(al, m,0);
    gtt = all * ( ar * ar + del2 ) + ar * (all * all + del2);
    OPS_ACC(gt, m,0)= gtt / (ar * ar + all * all + 2.00 * del2);
  }

  }
}
