//
// auto-generated by ops.py
//

int xdim0_save_kernel;
int xdim1_save_kernel;
int xdim2_save_kernel;
int xdim3_save_kernel;
int xdim4_save_kernel;
int xdim5_save_kernel;


//user function



void save_kernel_c_wrapper(
  double * restrict rho_old_p,
  double * restrict rhou_old_p,
  double * restrict rhoE_old_p,
  double * restrict rho_new_p,
  double * restrict rhou_new_p,
  double * restrict rhoE_new_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    ptr_double rho_old = { rho_old_p + n_x*1};
    ptr_double rhou_old = { rhou_old_p + n_x*1};
    ptr_double rhoE_old = { rhoE_old_p + n_x*1};
    const ptr_double rho_new = { rho_new_p + n_x*1};
    const ptr_double rhou_new = { rhou_new_p + n_x*1};
    const ptr_double rhoE_new = { rhoE_new_p + n_x*1};
    
  OPS_ACC(rho_old, 0)=OPS_ACC(rho_new, 0);
  OPS_ACC(rhou_old, 0)=OPS_ACC(rhou_new, 0);
  OPS_ACC(rhoE_old, 0)=OPS_ACC(rhoE_new, 0);
  
  }
}
