//
// auto-generated by ops.py
//

int xdim0_tvd_kernel;
int xdim1_tvd_kernel;


//user function



void tvd_kernel_c_wrapper(
  double * restrict tht_p,
  double * restrict ep2_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    #ifdef OPS_SOA
    const ptrm_double tht = { tht_p + n_x*1, xdim0_tvd_kernel};
    #else
    const ptrm_double tht = { tht_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    ptrm_double ep2 = { ep2_p + n_x*1, xdim1_tvd_kernel};
    #else
    ptrm_double ep2 = { ep2_p + n_x*1, 3};
    #endif
    
  double maxim;
  for (int m=0; m < 3 ;m++) {
    if (OPS_ACC(tht, m,0) > OPS_ACC(tht, m,1))
      maxim = OPS_ACC(tht, m,0);
    else
      maxim = OPS_ACC(tht, m,1);
    OPS_ACC(ep2, m,0) = akap2 * maxim;
  }

  }
}
