//
// auto-generated by ops.py
//

int xdim0_updateRK3_kernel;
int xdim1_updateRK3_kernel;
int xdim2_updateRK3_kernel;
int xdim3_updateRK3_kernel;
int xdim4_updateRK3_kernel;
int xdim5_updateRK3_kernel;
int xdim6_updateRK3_kernel;
int xdim7_updateRK3_kernel;
int xdim8_updateRK3_kernel;


//user function



void updateRK3_kernel_c_wrapper(
  double * restrict rho_new_p,
  double * restrict rhou_new_p,
  double * restrict rhoE_new_p,
  double * restrict rho_old_p,
  double * restrict rhou_old_p,
  double * restrict rhoE_old_p,
  double * restrict rho_res_p,
  double * restrict rhou_res_p,
  double * restrict rhoE_res_p,
  const double * restrict a1,
  const double * restrict a2,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    ptr_double rho_new = { rho_new_p + n_x*1};
    ptr_double rhou_new = { rhou_new_p + n_x*1};
    ptr_double rhoE_new = { rhoE_new_p + n_x*1};
    ptr_double rho_old = { rho_old_p + n_x*1};
    ptr_double rhou_old = { rhou_old_p + n_x*1};
    ptr_double rhoE_old = { rhoE_old_p + n_x*1};
    ptr_double rho_res = { rho_res_p + n_x*1};
    ptr_double rhou_res = { rhou_res_p + n_x*1};
    ptr_double rhoE_res = { rhoE_res_p + n_x*1};
    

  OPS_ACC(rho_new, 0) = OPS_ACC(rho_old, 0) + dt * a1[0] * (-OPS_ACC(rho_res, 0));
  OPS_ACC(rhou_new, 0) = OPS_ACC(rhou_old, 0) + dt * a1[0] * (-OPS_ACC(rhou_res, 0));
  OPS_ACC(rhoE_new, 0) = OPS_ACC(rhoE_old, 0) + dt * a1[0] * (-OPS_ACC(rhoE_res, 0));

  OPS_ACC(rho_old, 0) = OPS_ACC(rho_old, 0) + dt * a2[0] * (-OPS_ACC(rho_res, 0));
  OPS_ACC(rhou_old, 0) = OPS_ACC(rhou_old, 0) + dt * a2[0] * (-OPS_ACC(rhou_res, 0));
  OPS_ACC(rhoE_old, 0) = OPS_ACC(rhoE_old, 0) + dt * a2[0] * (-OPS_ACC(rhoE_res, 0));
  OPS_ACC(rho_res, 0) = 0;
  OPS_ACC(rhou_res, 0) = 0;
  OPS_ACC(rhoE_res, 0) = 0;
  
  }
}
