//
// auto-generated by ops.py
//

int xdim0_vars_kernel;
int xdim1_vars_kernel;
int xdim2_vars_kernel;
int xdim3_vars_kernel;
int xdim4_vars_kernel;


//user function



void vars_kernel_c_wrapper(
  double * restrict alam_p,
  double * restrict al_p,
  double * restrict gt_p,
  double * restrict cmp_p,
  double * restrict cf_p,
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    #ifdef OPS_SOA
    const ptrm_double alam = { alam_p + n_x*1, xdim0_vars_kernel};
    #else
    const ptrm_double alam = { alam_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    const ptrm_double al = { al_p + n_x*1, xdim1_vars_kernel};
    #else
    const ptrm_double al = { al_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    const ptrm_double gt = { gt_p + n_x*1, xdim2_vars_kernel};
    #else
    const ptrm_double gt = { gt_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    ptrm_double cmp = { cmp_p + n_x*1, xdim3_vars_kernel};
    #else
    ptrm_double cmp = { cmp_p + n_x*1, 3};
    #endif
    #ifdef OPS_SOA
    ptrm_double cf = { cf_p + n_x*1, xdim4_vars_kernel};
    #else
    ptrm_double cf = { cf_p + n_x*1, 3};
    #endif
    
  double  anu, aaa, ga, qf, ww;
  for (int m=0; m < 3 ;m++) {
    anu = OPS_ACC(alam, m,0);
    aaa = OPS_ACC(al, m,0);
    ga = aaa * ( OPS_ACC(gt, m,1) - OPS_ACC(gt, m,0)) / (pow(aaa,2.0) + del2);
    qf = sqrt ( con + pow(anu,2.0));
    OPS_ACC(cmp, m,0) = 0.50 * qf;
    ww = anu + OPS_ACC(cmp, m,0) * ga;
    qf = sqrt(con + pow(ww,2.0));
    OPS_ACC(cf, m,0) = qf;
  }

  }
}
