//
// auto-generated by ops.py//

#include "./OpenACC/adi_burger_3D_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "initKernel_openacc_kernel_c.c"
#include "CopyUVW_openacc_kernel_c.c"
#include "preprocessX_openacc_kernel_c.c"
#include "preprocessY_openacc_kernel_c.c"
#include "preprocessZ_openacc_kernel_c.c"
