//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_CopyUVW;
int ydim0_CopyUVW;
int xdim1_CopyUVW;
int ydim1_CopyUVW;
int xdim2_CopyUVW;
int ydim2_CopyUVW;
int xdim3_CopyUVW;
int ydim3_CopyUVW;
int xdim4_CopyUVW;
int ydim4_CopyUVW;
int xdim5_CopyUVW;
int ydim5_CopyUVW;

//user function
inline 
void CopyUVW(const ptr_double u,
  const ptr_double v,
  const ptr_double w,
  ptr_double uStar,
  ptr_double vStar,
  ptr_double wStar) {
    OPS_ACC(uStar, 0, 0, 0) = OPS_ACC(u, 0, 0, 0);
    OPS_ACC(vStar, 0, 0, 0) = OPS_ACC(v, 0, 0, 0);
    OPS_ACC(wStar, 0, 0, 0) = OPS_ACC(w, 0, 0, 0);
}


void CopyUVW_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double *p_a3,
  double *p_a4,
  double *p_a5,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2,p_a3,p_a4,p_a5)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_CopyUVW*1*1 + n_z*xdim0_CopyUVW*ydim0_CopyUVW*1*1, xdim0_CopyUVW, ydim0_CopyUVW};
        const ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_CopyUVW*1*1 + n_z*xdim1_CopyUVW*ydim1_CopyUVW*1*1, xdim1_CopyUVW, ydim1_CopyUVW};
        const ptr_double ptr2 = {  p_a2 + n_x*1*1 + n_y*xdim2_CopyUVW*1*1 + n_z*xdim2_CopyUVW*ydim2_CopyUVW*1*1, xdim2_CopyUVW, ydim2_CopyUVW};
        ptr_double ptr3 = {  p_a3 + n_x*1*1 + n_y*xdim3_CopyUVW*1*1 + n_z*xdim3_CopyUVW*ydim3_CopyUVW*1*1, xdim3_CopyUVW, ydim3_CopyUVW};
        ptr_double ptr4 = {  p_a4 + n_x*1*1 + n_y*xdim4_CopyUVW*1*1 + n_z*xdim4_CopyUVW*ydim4_CopyUVW*1*1, xdim4_CopyUVW, ydim4_CopyUVW};
        ptr_double ptr5 = {  p_a5 + n_x*1*1 + n_y*xdim5_CopyUVW*1*1 + n_z*xdim5_CopyUVW*ydim5_CopyUVW*1*1, xdim5_CopyUVW, ydim5_CopyUVW};
        CopyUVW( ptr0,
          ptr1,
          ptr2,
          ptr3,
          ptr4,
          ptr5 );

      }
    }
  }
}
