//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_preprocessZ;
int ydim0_preprocessZ;
int xdim1_preprocessZ;
int ydim1_preprocessZ;
int xdim2_preprocessZ;
int ydim2_preprocessZ;
int xdim4_preprocessZ;
int ydim4_preprocessZ;
int xdim5_preprocessZ;
int ydim5_preprocessZ;
int xdim6_preprocessZ;
int ydim6_preprocessZ;
int xdim7_preprocessZ;
int ydim7_preprocessZ;
int xdim8_preprocessZ;
int ydim8_preprocessZ;
int xdim9_preprocessZ;
int ydim9_preprocessZ;
int xdim10_preprocessZ;
int ydim10_preprocessZ;
int xdim11_preprocessZ;
int ydim11_preprocessZ;
int xdim12_preprocessZ;
int ydim12_preprocessZ;

//user function
inline 
void preprocessZ(const ptr_double u,
  const ptr_double v,
  const ptr_double w,
  const double *time,
  ptr_double a,
  ptr_double b,
  ptr_double c,
  ptr_double du,
  ptr_double dv,
  ptr_double dw,
  ACC<double> resU,
  ACC<double> resV,
  ACC<double> resW,
  int *idx) {
    OPS_ACC(resU, 0, 0, 0) = 0;
    OPS_ACC(resV, 0, 0, 0) = 0;
    OPS_ACC(resW, 0, 0, 0) = 0;
    const double x{h * idx[0]};
    const double y{h * idx[1]};
    const double z{h * idx[2]};
    const double t{*time};
    if (idx[0] == 0 || idx[0] == nx - 1 || idx[1] == 0 || idx[1] == ny - 1 ||
        idx[2] == 0 || idx[2] == nz - 1) {
        OPS_ACC(a, 0, 0, 0) = 0;
        OPS_ACC(b, 0, 0, 0) = 1;
        OPS_ACC(c, 0, 0, 0) = 0;
        OPS_ACC(du, 0, 0, 0) = 2 * exp(-t / Re) * sin(x) * sin(y) * cos(z) /
                      (Re * (cos(x) * sin(y) * cos(z) + 1));
        OPS_ACC(dv, 0, 0, 0) = -2 * exp(-t / Re) * cos(x) * cos(y) * cos(z) /
                      (Re * (cos(x) * sin(y) * cos(z) + 1));
        OPS_ACC(dw, 0, 0, 0) = 2 * exp(-t / Re) * cos(x) * sin(y) * sin(z) /
                      (Re * (cos(x) * sin(y) * cos(z) + 1));
    } else {
        OPS_ACC(a, 0, 0, 0) = -r1 * OPS_ACC(w, 0, 0, 0) - r2;
        OPS_ACC(b, 0, 0, 0) = 1 + 2 * r2;
        OPS_ACC(c, 0, 0, 0) = r1 * OPS_ACC(w, 0, 0, 0) - r2;
        OPS_ACC(du, 0, 0, 0) = (r1 * OPS_ACC(v, 0, 0, 0) + r2) * OPS_ACC(u, 0, -1, 0) +
                      (-r1 * OPS_ACC(v, 0, 0, 0) + r2) * OPS_ACC(u, 0, 1, 0) +
                      (r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(u, -1, 0, 0) +
                      (-r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(u, 1, 0, 0) +
                      (1 - 4 * r2) * OPS_ACC(u, 0, 0, 0);
        OPS_ACC(dv, 0, 0, 0) = (r1 * OPS_ACC(v, 0, 0, 0) + r2) * OPS_ACC(v, 0, -1, 0) +
                      (-r1 * OPS_ACC(v, 0, 0, 0) + r2) * OPS_ACC(v, 0, 1, 0) +
                      (r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(v, -1, 0, 0) +
                      (-r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(v, 1, 0, 0) +
                      (1 - 4 * r2) * OPS_ACC(v, 0, 0, 0);
        OPS_ACC(dw, 0, 0, 0) = (r1 * OPS_ACC(v, 0, 0, 0) + r2) * OPS_ACC(w, 0, -1, 0) +
                      (-r1 * OPS_ACC(v, 0, 0, 0) + r2) * OPS_ACC(w, 0, 1, 0) +
                      (r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(w, -1, 0, 0) +
                      (-r1 * OPS_ACC(u, 0, 0, 0) + r2) * OPS_ACC(w, 1, 0, 0) +
                      (1 - 4 * r2) * OPS_ACC(w, 0, 0, 0);
    }
}


void preprocessZ_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double p_a3,
  double *p_a4,
  double *p_a5,
  double *p_a6,
  double *p_a7,
  double *p_a8,
  double *p_a9,
  double *p_a10,
  double *p_a11,
  double *p_a12,
  int *p_a13,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2,p_a4,p_a5,p_a6,p_a7,p_a8,p_a9,p_a10,p_a11,p_a12)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        const ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_preprocessZ*1*1 + n_z*xdim0_preprocessZ*ydim0_preprocessZ*1*1, xdim0_preprocessZ, ydim0_preprocessZ};
        const ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_preprocessZ*1*1 + n_z*xdim1_preprocessZ*ydim1_preprocessZ*1*1, xdim1_preprocessZ, ydim1_preprocessZ};
        const ptr_double ptr2 = {  p_a2 + n_x*1*1 + n_y*xdim2_preprocessZ*1*1 + n_z*xdim2_preprocessZ*ydim2_preprocessZ*1*1, xdim2_preprocessZ, ydim2_preprocessZ};
        ptr_double ptr4 = {  p_a4 + n_x*1*1 + n_y*xdim4_preprocessZ*1*1 + n_z*xdim4_preprocessZ*ydim4_preprocessZ*1*1, xdim4_preprocessZ, ydim4_preprocessZ};
        ptr_double ptr5 = {  p_a5 + n_x*1*1 + n_y*xdim5_preprocessZ*1*1 + n_z*xdim5_preprocessZ*ydim5_preprocessZ*1*1, xdim5_preprocessZ, ydim5_preprocessZ};
        ptr_double ptr6 = {  p_a6 + n_x*1*1 + n_y*xdim6_preprocessZ*1*1 + n_z*xdim6_preprocessZ*ydim6_preprocessZ*1*1, xdim6_preprocessZ, ydim6_preprocessZ};
        ptr_double ptr7 = {  p_a7 + n_x*1*1 + n_y*xdim7_preprocessZ*1*1 + n_z*xdim7_preprocessZ*ydim7_preprocessZ*1*1, xdim7_preprocessZ, ydim7_preprocessZ};
        ptr_double ptr8 = {  p_a8 + n_x*1*1 + n_y*xdim8_preprocessZ*1*1 + n_z*xdim8_preprocessZ*ydim8_preprocessZ*1*1, xdim8_preprocessZ, ydim8_preprocessZ};
        ptr_double ptr9 = {  p_a9 + n_x*1*1 + n_y*xdim9_preprocessZ*1*1 + n_z*xdim9_preprocessZ*ydim9_preprocessZ*1*1, xdim9_preprocessZ, ydim9_preprocessZ};
        ptr_double ptr10 = {  p_a10 + n_x*1*1 + n_y*xdim10_preprocessZ*1*1 + n_z*xdim10_preprocessZ*ydim10_preprocessZ*1*1, xdim10_preprocessZ, ydim10_preprocessZ};
        ptr_double ptr11 = {  p_a11 + n_x*1*1 + n_y*xdim11_preprocessZ*1*1 + n_z*xdim11_preprocessZ*ydim11_preprocessZ*1*1, xdim11_preprocessZ, ydim11_preprocessZ};
        ptr_double ptr12 = {  p_a12 + n_x*1*1 + n_y*xdim12_preprocessZ*1*1 + n_z*xdim12_preprocessZ*ydim12_preprocessZ*1*1, xdim12_preprocessZ, ydim12_preprocessZ};
        preprocessZ( ptr0,
          ptr1,
          ptr2,
           &p_a3,
          ptr4,
          ptr5,
          ptr6,
          ptr7,
          ptr8,
          ptr9,
          ptr10,
          ptr11,
          ptr12,
          arg_idx );

      }
    }
  }
}
