//
// auto-generated by ops.py
//

#define OPS_2D
#include <math.h>
#include "./MPI_inline/mgrid_common.h"
//user kernel files
#include "mgrid_populate_kernel_1_mpiinline_kernel_c.c"
#include "mgrid_prolong_kernel_mpiinline_kernel_c.c"
#include "prolong_check_mpiinline_kernel_c.c"
#include "mgrid_populate_kernel_3_mpiinline_kernel_c.c"
#include "mgrid_restrict_kernel_mpiinline_kernel_c.c"
#include "restrict_check_mpiinline_kernel_c.c"
