//
// auto-generated by ops.py
//

int xdim0_mgrid_restrict_kernel;
int xdim1_mgrid_restrict_kernel;


//user function



void mgrid_restrict_kernel_c_wrapper(
  double * restrict fine_p,
  double * restrict coarse_p,
  int * restrict idx,
  const int * restrict global_idx,
  const int * restrict stride_0,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double fine = { fine_p + n_x*stride_0[0]*1 + n_y*stride_0[1] * xdim0_mgrid_restrict_kernel*1, xdim0_mgrid_restrict_kernel};
      ptr_double coarse = { coarse_p + n_x*1 + n_y * xdim1_mgrid_restrict_kernel*1, xdim1_mgrid_restrict_kernel};
      

  OPS_ACC(coarse, 0,0) = OPS_ACC(fine, 0,0);

    }
  }
}
