//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_complex_populate_kernel;

//user function
inline 
void complex_populate_kernel(ptr_complexd val,
  complexd *red,
  int *idx) {
  OPS_ACC(val, 0,0).real((double)idx[0]);
  OPS_ACC(val, 0,0).imag((double)idx[1]);
  *red += OPS_ACC(val, 0,0);
}


void complex_populate_kernel_c_wrapper(
  complexd *p_a0,
  complexd *p_a1,
  int *p_a2,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  complexd p_a1_0 = p_a1[0];
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0) reduction(+:p_a1_0)
  #pragma acc loop reduction(+:p_a1_0)
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop reduction(+:p_a1_0)
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      ptr_complexd ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_complex_populate_kernel*1*1, xdim0_complex_populate_kernel};
      complex_populate_kernel( ptr0,
           &p_a1_0,arg_idx );

    }
  }
  p_a1[0] = p_a1_0;
}
